### ISSUE TITLE
useScheduledWeather doesn't exist in cofig

### ISSUE THREAD

**Issue by CodexisPhantom** [Renewed-Scripts/Renewed-Weathersync#6]
### Summary

You write scheduleWeather instead of useScheduledWeather in config

### Reproduction

Just start the script in wait for txadmin schedule restart and then nothing append

### Expected behavior

Normally the time should change

### Actual behavior

Nothing append

### Last Updated

today

### Resource Rename

Renewed-Weathersync

**Comment by FjamZoo** [comment]
Been fixed in latest.

Thanks for sharing
