### ISSUE TITLE
snow

### ISSUE THREAD

**Issue by xrtw** [Renewed-Scripts/Renewed-Weathersync#8]
### Summary

doesn't sync if it's snowing

### Reproduction

RegisterNetEvent('qb-weathersync:client:EnableSync', function()
    playerState.syncWeather = true
end)

### Expected behavior

it should snow if i have
`if Config.decemberSnow and currentMonth == 11 or currentMonth == 12 then
        return getDecemberSnow()
    end`

### Actual behavior

no snow

### Last Updated

today

### Resource Rename

no

**Comment by soniXx123** [comment]
same we don't have snow as well only if we restart the resource.

**Comment by Scullyy** [comment]
I can't seem to repro this myself using default logic provided in the script. Did you make any edits?

**Comment by FjamZoo** [comment]
I couldnt get a issue after, could u try the latest update?

That seems to be the only issue I can think of

**Comment by Borreke0** [comment]
Having the same issue here with stock syncs.

The snow does not sync when deploying after selecting a character (playerstate syncs print true tho)
But does sync after entering and leaving an instance like a house/apartement/...

But can't seem to fix it to let it sync on spawn.. As the weather system prints as being synced but it isn't

I am at latest commits.

**Comment by Borreke0** [comment]
Fixed it for us by adding a new sync after this wait:
https://github.com/qbcore-framework/qb-multicharacter/blob/main/client/main.lua#L165

**Comment by bluelineparabellum** [comment]
Snow is freezing players when it shows on ground all of a sudden and when it suddenly disappears
